### ISSUE TITLE
[教程大纲] 如何安装 Jenkins 插件

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-zh#368]
本段时间大致要介绍的内容包括：

* 插件管理界面的简介
* 国内插件中心的配置
  * 使用问题，请在论坛交流 https://community.jenkins-zh.cn/t/jenkins/26
  * 官方源 `https://updates.jenkins.io/update-center.json`
  * 国内源 `https://updates.jenkins-zh.cn/update-center.json`
* 官方插件网站 https://plugins.jenkins.io/
* 插件如何选择
  * 插件管理界面搜索
  * http://plugins.jenkins.io/
  * https://github.com/jenkinsci/
* Jenkins 的插件目录介绍

**Comment by LinuxSuRen** [comment]
已完成

**Comment by lcysgsg** [comment]
我想知道右下角的 “Jenkins 中文社区” 链接是哪里来的？希望能补充这一部分。

我在服务器上通过`docker`启动的`jenkins`里安装插件遇到了困难，尝试单纯的设置了镜像也没有效果，看到分析是因为需要更新证书。或许是要安装这个 [localization-zh-cn-plugin](https://github.com/jenkinsci/localization-zh-cn-plugin) 插件帮助更新镜像？但是我不会 Java，[Prepare a Java Source File for Localization](https://www.jenkins.io/zh/doc/developer/internationalization/prepare-a-java-source-file/) 根本看不懂怎么做，`jcli` 运行起来跟文档对不上... 所以，希望安装插件的教程能补充这一点。
我会继续尝试[Prepare a Java Source File for Localization](https://www.jenkins.io/zh/doc/developer/internationalization/prepare-a-java-source-file/)这一部分，如果我成功了，我就来帮忙补充这一点。

（为什么配置镜像这么困难？人已经麻了T.T）

**Comment by LinuxSuRen** [comment]
> 我想知道右下角的 “Jenkins 中文社区” 链接是哪里来的？希望能补充这一部分。

这个问题和你安装插件并没有关系。

> 尝试单纯的设置了镜像也没有效果

你这里说的镜像指的是什么？

另外，之前由 Jenkins 中文社区提供的“插件更新中心”国内源，由于社区缺乏资金的支持，目前无法提供服务器。

**Comment by lcysgsg** [comment]
感谢回复。

> > 尝试单纯的设置了镜像也没有效果
> 
> 你这里说的镜像指的是什么？

DashBoard -> Plugin Manager -> Advanced -> Update Site 设置成了 `https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json`，没有效果，看到说是还需要更新证书。又按换成 `https://updates.jenkins-zh.cn/update-center.json` 配合右下角不知怎么出现的超链接 “Jenkins  中文社区（我找不到教程在哪了...）”中的“使用”按钮，但是我没有这个超链接，现在就卡在这一步。

安装插件会失败显示的错误信息：
``` 
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
Also:   java.net.SocketException: Broken pipe (Write failed)
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:380)
Caused: javax.net.ssl.SSLException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:144)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1418)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1324)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3099)
	at java.base/java.net.URLConnection.getHeaderFieldLong(URLConnection.java:636)
	at java.base/java.net.URLConnection.getContentLengthLong(URLConnection.java:508)
	at java.base/java.net.URLConnection.getContentLength(URLConnection.java:492)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:394)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1266)
Caused: javax.net.ssl.SSLException: Connection reset
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1282)
Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/structs/1.23/structs.hpi to /var/jenkins_home/plugins/structs.jpi.tmp
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1289)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/structs/1.23/structs.hpi
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1323)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1871)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2164)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1845)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

> 
> 另外，之前由 Jenkins 中文社区提供的“插件更新中心”国内源，由于社区缺乏资金的支持，目前无法提供服务器。

唉。
使用清华源是可以的吗？但我不懂怎么更新证书... 
现在插件安装不了的问题就是连接不稳定，也许配置 http proxy 是更简单的办法？

**Comment by LinuxSuRen** [comment]
https://community.jenkins-zh.cn/t/jenkins/26

**Comment by samxxxxx** [comment]
@lcysgsg 你的下载问题解决了吗 搞了二天了 一直不行 镜像源换来换去也不行

**Comment by samxxxxx** [comment]
@LinuxSuRen 请问windows jenkins的插件下载有什么办法吗？我很奇怪我家里面的电脑是可以的，不需要改镜像站，但是公司的又不行。

**Comment by LinuxSuRen** [comment]
> 家里面的电脑是可以的，不需要改镜像站，但是公司的又不行

这个就是个网络问题，没有非常好的办法

**Comment by samxxxxx** [comment]
> > 家里面的电脑是可以的，不需要改镜像站，但是公司的又不行
> 
> 这个就是个网络问题，没有非常好的办法

感谢回复。我确定不是网络问题，我是在vmware里测试的，操作系统是win10，在docker内运行jenkins是正常下载插件。但是在win10下就不行。显示的都是这个提示`unable to find valid certification path to requested target`
